### ISSUE TITLE
broken by cargo-auditable changes in nixpkgs

### ISSUE THREAD

**Issue by andresilva** [nix-community/fenix#102]
This seems to have been broken by https://github.com/NixOS/nixpkgs/pull/223320. It's not obvious to me what the problem is.

**Comment by figsoda** [comment]
should be fixed by https://github.com/NixOS/nixpkgs/pull/226023, once that gets into unstable

**Comment by andresilva** [comment]
Thanks for the fast turnaround! This is already in `nixos-unstable-small`, I've tested it and it fixes the issue.
