### ISSUE TITLE
CI fails, no new versions

### ISSUE THREAD

**Issue by RobWalt** [nix-community/fenix#138]
The CI has been stuck for 4 days or so since there seems to be no space left on the CI servers.

I just wanted to let you know @figsoda . 

Because of this, the new rust toolchain version 1.76 is not available with this repo.

Link to failing CI for a random day: https://github.com/nix-community/fenix/actions/runs/7882575882/job/21508007651

**Comment by figsoda** [comment]
Thanks for reporting this, it seems to have fixed itself: https://github.com/nix-community/fenix/actions/runs/7897318947

I think there might have been some issues with github actions? because the previous CI attempts kept running out of disk space

**Comment by RobWalt** [comment]
Yeah I've searched the web for some hints and it seems like this already happened in the past when the github team deployed some new changes. Cool that it resolved itself 😅
