### ISSUE TITLE
Request: Expose latest stable version.

### ISSUE THREAD

**Issue by gcoakes** [nix-community/fenix#14]
I'd like to use fenix to customize the targets in my toolchain while still using stable. Is feasible to add the latest stable release to fenix?

**Comment by figsoda** [comment]
Stable and beta toolchains are now included. You can now use things like
`fenix.packages.x86_64-linux.stable.defaultToolchain`
`fenix.packages.x86_64-linux.stable.rustc`
`fenix.packages.x86_64-linux.targets.wasm32-unknown-unknown.stable.rust-std`
Also in overlay, `rust-nightly` is renamed to `fenix`.
