### ISSUE TITLE
No way to (easily) get specific nightly version

### ISSUE THREAD

**Issue by cab404** [nix-community/fenix#16]
First of all, thanks for the project!
It's a lot nicer to use with flakes than mozilla-overlay, and saved me a lot of time!

I want a specific nightly version (for MIRAI), and the only way I can get it is via searching entire git history.
Adding tags would help, and should be easy enough to integrate into gh actions.

**Comment by cab404** [comment]
Other way would be storing every nightly release json. That would allow using consistent (and new) fenix versions.
@figsoda do you have any ideas about that? I would like to work on a PR.

**Comment by figsoda** [comment]
I personally disagree on storing every nightly release because this would make the repository a lot heavier. I would prefer something like
```
channelOf = { channel, date, sha256 }: {
  rustc = [...],
  cargo = [...],
  [...]
  withComponents = [...],
  toolchain = [...],
  minimalToolchain = [...],
  defaultToolchain = [...],
  completeToolchain = [...],
};
```

**Comment by cab404** [comment]
> I personally disagree on storing every nightly release because this would make the repository a lot heavier. I would prefer something like
> 
> ```
> channelOf = { channel, date, sha256 }: {
>   rustc = [...],
>   cargo = [...],
>   [...]
>   withComponents = [...],
>   toolchain = [...],
>   minimalToolchain = [...],
>   defaultToolchain = [...],
>   completeToolchain = [...],
> };
> ```

Looks fine to me as well, will work on a PR this weekend.
