### ISSUE TITLE
No commits in last 10 days

### ISSUE THREAD

**Issue by dpc** [nix-community/fenix#161]
I was looking for new Rust release, and IIUC in the past there was a daily commit, and for the last 10 days there are none. Seems like a cronjob somewhere not running?

**Comment by RobWalt** [comment]
I'm already working on a fix. #160 seems like the first necessary step

**Comment by figsoda** [comment]
Thanks for the report, https://github.com/nix-community/fenix/commit/bd901287e77667fc7838de479de852dc0f149fb0 should fix the issue
