### ISSUE TITLE
clippy-preview fails to build on darwin

### ISSUE THREAD

**Issue by sandhose** [nix-community/fenix#17]
When trying to build `clippy-preview` on Darwin, I get this error:

```
error: builder for '/nix/store/mqk84723a1dxksb9r1nswmlqac4r2qjy-clippy-preview-nightly-2021-05-10.drv' failed with exit code 127;
       last 10 log lines:
       > no Makefile, doing nothing
       > installing
       > patching script interpreter paths in install.sh
       > install.sh: interpreter directive changed from "#!/bin/bash" to "/nix/store/pcjan45rssdn01cxx3sjg70avjg6c3ni-bash-4.4-p23/bin/bash"
       > install: creating uninstall script at /nix/store/b57vkgbkbksxgpndjcq6786qlv0q1bjr-clippy-preview-nightly-2021-05-10/lib/rustlib/uninstall.sh
       > install: installing component 'clippy-preview'
       >
       >     clippy installed.
       >
       > /nix/store/sv61k1l9fapkn1dzlvclqjl5i1sbhfyw-stdenv-darwin/setup: line 1341: patchelf: command not found
       For full logs, run 'nix log /nix/store/mqk84723a1dxksb9r1nswmlqac4r2qjy-clippy-preview-nightly-2021-05-10.drv'.
```

It happens because of this: https://github.com/nix-community/fenix/blob/8730359eea7a6004b75c571afb885061efd54990/lib/mk-toolchain.nix#L42-L46
`patchelf` does not exist on darwin, it's equivalent would be `install_name_tool`.

In nixpkgs, patching the rpath for clippy on darwin looks like this: https://github.com/NixOS/nixpkgs/blob/91a247a1f0346a653a025e391527287ec786b0c2/pkgs/development/compilers/rust/clippy.nix#L23-L25

**Comment by figsoda** [comment]
Can you test the master now? I hope https://github.com/nix-community/fenix/commit/93ca93f5d9785bcc9ceb1b7743afa1250ab1e9dc fixed it. I don't have a darwin machine, but I am planning to add more tests to the ci.

**Comment by sandhose** [comment]
[It builds](https://github.com/sandhose/nixconf/runs/2758146020) and runs on my mac, thanks a lot!
I'm also using GitHub Actions to build my nixos/darwin configurations and it works well with the `macos` hosts. You can take a look at my workflow [here](https://github.com/sandhose/nixconf/blob/ac012e137e3173feb199ae0b785ebb8485b323e4/.github/workflows/build.yaml#L17). Seeing your [current workflow](https://github.com/nix-community/fenix/blob/main/.github/workflows/ci.yml), your jobs should work as-is by just setting the `runs-on` to `macos-latest` instead of `ubuntu-latest` using a [`matrix`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).
