### ISSUE TITLE
rustlib binaries don't get patched

### ISSUE THREAD

**Issue by cab404** [nix-community/fenix#18]
If you use llvm-tools-preview, none of the binaries in `/lib/rustlib/x86_64-unknown-linux-gnu/bin/`get patched. Thus, cargo-binutils do not work.

```
...
pid 2289500] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 2289500] execve("/nix/store/jym3ral8lr8c9jaqz3d1vdb88nwxjrd3-rust-mixed/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld", ["/nix/store/jym3ral8lr8c9jaqz3d1v"...], 0x7ffe23793788 /* 162 vars */) = -1 ENOENT (No such file or directory)
[pid 2289500] exit_group(127)           = ?
[pid 2289486] <... clone resumed>)      = 2289500
...
```

Can be reproduced with any toolchain version.

1. `cargo install cargo-binutils`
2. `rust-lld`

**Comment by figsoda** [comment]
should be fixed by https://github.com/nix-community/fenix/commit/164b7a893a2816e8def495968a1a7ce149b49489
