### ISSUE TITLE
`buildVscodeExtension` fails because missing `pname`

### ISSUE THREAD

**Issue by ghost** [nix-community/fenix#186]
hey there,

after having run nix flake update i'm getting a build fail with

       error: function 'buildVscodeExtension' called without required argument 'pname'

       at /nix/store/sgbj0n22b3p8rfvmp46c6qha0qax4wyd-source/pkgs/applications/editors/vscode/extensions/vscode-utils.nix:13:5:
       
i'm getting this on minimal, default and complete toolchain (allbeit it all of them with the with components including rust-analyzer. which will be triggering the vscode extension build.

is there a way for me to reasonably override this? sorry i rlly am just not feeling like debugging this nix bit again. if you wanna close the issue feel free to, more so meant as a hey this is thing that happened apparently. i can provide more of the setup i have if you need me to. i'm doing stuff with crane down the line.

best regards

**Comment by yzx9** [comment]
related: #184

**Comment by justDeeevin** [comment]
Any workaround here? This is entirely blocking my current use of fenix

**Comment by bodby** [comment]
> Any workaround here? This is entirely blocking my current use of fenix

Fork and then merge #184.

**Comment by bryango** [comment]
I am trying to fix this upstream at NixOS/nixpkgs#361052 as this also affects other projects.

**Comment by yzx9** [comment]
NixOS/nixpkgs#361052 from @bryango has been merged! This should be solved after [next bump](https://status.nixos.org/）
