### ISSUE TITLE
More examples 

### ISSUE THREAD

**Issue by dpc** [nix-community/fenix#19]
Hi. I've been using NixOS for a while now, but I don't consider myself a power user yet. Flakes are a new concept to me, and it seems great.

I am able to somewhat use this repo for my Rust projects, but I'm having a really hard time with details and non-trivial addons. What would really, really help are examples of existing, non-trivial projects with `flake.nix` using `fenix`.

BTW. The https://github.com/nix-community/fenix#usage is not really helpful for someone like me. It's not clear what are these commented out parts for and how to make them work. I was only able to somewhat figure them out after reading more about flakes, and looking up how some other flakes were working. Unfortunately what I was able to find was not using Rust/`fenix`. Not trying to be critical - just hoping that my PoV can help make this repo more accessible and thus useful.

Thanks!

**Comment by dpc** [comment]
OK. So after following https://serokell.io/blog/practical-nix-flakes I've discovered that examples in https://serokell.io/blog/practical-nix-flakes get by unfolded, and these were exactly much closer to what I need and some pieces of puzzle fell in place.

Still, it seems to me that having example rust project (like some cli utility / web server or something) with a `flake.nix` in it, linked from README.md would be helpful.

**Comment by figsoda** [comment]
there are flake.nix examples in readme in case you didnt see
