### ISSUE TITLE
Comparison to rust-overlay

### ISSUE THREAD

**Issue by winterqt** [nix-community/fenix#22]
What are the (dis)advantages of using fenix over [rust-overlay](https://github.com/oxalica/rust-overlay], if any?

**Comment by figsoda** [comment]
rust-overlay is a heaver library with support for [rustup toolchain files](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) and includes all the nightly manifests from 2018. It is a drop in replacement for [nixpkgs-mozilla](https://github.com/mozilla/nixpkgs-mozilla). fenix is more of lightweight alternative to [rustup](https://github.com/rust-lang/rustup).
