### ISSUE TITLE
Document how to use the overlay as an ordinary user

### ISSUE THREAD

**Issue by bbqsrc** [nix-community/fenix#24]
It would be helpful to document how to add the user overlay for fenix and that to install a stable toolchain, this works:

```
nix-env -iA nixos.fenix.stable.defaultToolchain
```

**Comment by figsoda** [comment]
I'm planning to rewrite the documentation in another format, something like [flake-utils](https://github.com/numtide/flake-utils)'s

**Comment by figsoda** [comment]
I rewrote the documentation and added some more details in #35, how does it look? do you have any changes you wan to make?

**Comment by figsoda** [comment]
i'm merging this. but feel free to give suggestions here or in a new issue
