### ISSUE TITLE
stdlib source?

### ISSUE THREAD

**Issue by dpc** [nix-community/fenix#37]
I tried `minimal` and `complete` and I don't see the stdlib source to point `RUST_SRC_PATH` to. Where should I look?

**Comment by figsoda** [comment]
either
`"${fenix.complete.rust-src}/lib/rustlib/src/rust/src"` if you are using it with the complete toolchain
or
`"${fenix.latest.rust-src}/lib/rustlib/src/rust/src"` if you are using it with the minimal toolchain
should work

**Comment by dpc** [comment]
Thank you.

Now I see it in the examples, but I guess maybe it should be listed here explicitly as well? https://github.com/nix-community/fenix#toolchain
