### ISSUE TITLE
Latest Nix version disallows reading flake.lock

### ISSUE THREAD

**Issue by sandhose** [nix-community/fenix#40]
`fenix` does not build anymore since https://github.com/NixOS/nix/commit/e5596113f7fc5e47e058bb15afdf75eee02ed95e.
It fails with the following error:
```
error: cannot read '/nix/store/hlmrcg7qdlna77vxv3j5lpk77ja6sd6d-source/flake.lock' because flake lock files can be out of sync

       at /nix/store/hlmrcg7qdlna77vxv3j5lpk77ja6sd6d-source/default.nix:120:16:

          119|   rust-analyzer-rev = substring 0 7
          120|     (fromJSON (readFile ./flake.lock)).nodes.rust-analyzer-src.locked.rev;
             |                ^
          121| in nightlyToolchains.${v} // rec {
(use '--show-trace' to show detailed location information)
```

It happens because the rust-analyzer version is extracted from the revision in the lockfile: https://github.com/nix-community/fenix/blob/e917dae2552d6d50797a718bffba34102af082bf/default.nix#L119-L120

There is another occurrence of reading the lockfile in the same file, but this one is probably fine because it is only needed when fenix is imported in a non-flake way: https://github.com/nix-community/fenix/blob/e917dae2552d6d50797a718bffba34102af082bf/default.nix#L5-L10

---

Related: https://github.com/NixOS/nix/pull/5250, https://github.com/NixOS/nix/issues/4639

**Comment by edolstra** [comment]
While this has been reverted upstream, it's not a good idea to read `flake.lock`. It's much better to use the inputs passed to the `outputs` function.
