### ISSUE TITLE
Installed `cargo` version does not match other components

### ISSUE THREAD

**Issue by msfjarvis** [nix-community/fenix#42]
I use Fenix has a nixpkgs overlay with this component configuration:

```nix
(fenix.complete.withComponents [
  "cargo"
  "clippy-preview"
  "rust-src"
  "rustc"
  "rustfmt-preview"
])
```

I just built a new home-manager generation and it seems the installed version of cargo does not match the rest of the components

```
; cargo --version
cargo 1.57.0-nightly (33ee5f82e 2021-09-17)
; rustfmt --version
rustfmt 1.4.37-nightly (aa8f2d4 2021-09-18)
; rustc --version
rustc 1.57.0-nightly (aa8f2d432 2021-09-18)
; cargo-clippy --version
clippy 0.1.57 (aa8f2d4 2021-09-18)
```

The full home-manager configuration I use can be found [here](https://github.com/msfjarvis/dotfiles/blob/ccb157239a8e3dbc4c6c4efbf206ef4cdf1b45da/nixos/home-manager.nix) if it is of interest.

**Comment by figsoda** [comment]
They all come from the same nightly release (2021-09-19, [manifest](https://static.rust-lang.org/dist/2021-09-19/channel-rust-nightly.toml)). I think they should be compatible even though they are not released the same day. Have you experienced any incompatibility? Does rustup have a different behavior?

**Comment by msfjarvis** [comment]
> They all come from the same nightly release (2021-09-19, [manifest](https://static.rust-lang.org/dist/2021-09-19/channel-rust-nightly.toml)). I think they should be compatible even though they are not released the same day. Have you experienced any incompatibility? Does rustup have a different behavior?

I had issues with a previous Nix generation where my builds kept failing asking me to use a specific nightly which I had rustc from but not cargo, switching to a new Nix generation today fixed that but still had the version mismatch so I figured I'd report it. If it's an upstream thing then I'll just close this issue and forward any such build fails to rust-lang/rust instead. Thanks for your time!
