### ISSUE TITLE
request: cached branch

### ISSUE THREAD

**Issue by nrdxp** [nix-community/fenix#47]
When trying to pull the rust-analyzer-nightly package from main I am having to build it from scratch even though I have nix-community cache setup. Reverting to a previous commit resolved the issue. Since it is a bit of a heavy build it would be nice to have some mechanism to know which commit to pull to get a cached build. Perhaps once a build is uploaded to cachix a `cached` branch can be incremented to the build commit.

Alternatively, some sort of status indicator in the Readme to indicate the cache status of a the current commit would also be helpful, but the branch would be nicer since one could use it as a flake input and be guaranteed to pull from the cache on lock updates.

**Comment by figsoda** [comment]
This current darwin build is failing in ci due to https://github.com/NixOS/nixpkgs/issues/103172 and causing the linux build to abort as well

I think a good idea is to have everything pushed to a staging branch first and merged into main once ci passes, the only (small) downside I can think of is contributors would have to target the staging branch

**Comment by figsoda** [comment]
I guess this can be closed now, feel free to reopen it if you have anything else to say

**Comment by nrdxp** [comment]
Just a note, I seem to be building rust-analyzer again, despite your workflow change. This is on the latest commit at the time of writing.

**Comment by figsoda** [comment]
Did you do `inputs.nixpkgs.follows = "nixpkgs"`? if so, that's probably why
ci cached against `c5ed8beb478a8ca035f033f659b60c89500a3034` and current nixos-unstable is `2fa862644fc15ecb525eb8cd0a60276f1c340c7c`

**Comment by nrdxp** [comment]
oh yeah duh, that explains it, thanks
