### ISSUE TITLE
rustc and cargo are missing attributes of a call to fromToolchainFile

### ISSUE THREAD

**Issue by lincolnauster** [nix-community/fenix#54]
It's possible I'm misunderstanding more than a few important things, but here's what I've run into.

I'm setting up code coverage in CI under Nix, and in doing so, I need a Rust toolchain with the "llvm-tools-preview" component so that grcov doesn't [silently error out](https://github.com/mozilla/grcov/issues/662). I have the following rust-toolchain.toml for this:

```toml
[toolchain]
channel = "nightly-2021-10-29"
components = [ "llvm-tools-preview" ]
profile = "minimal"
```

I'm then makeRustPlatform'ing with the following definition:

```nix
{ # <flake outputs snip>
    rust = let toolchain = fenix.packages.x86_64-linux.fromToolchainFile {
            dir = ./.; # I'll deal with the sha256 later :)
          };
      in
        pkgs.makeRustPlatform {
          rustc = toolchain.rustc;
          cargo = toolchain.cargo;
        };
}
```

My CI scripts are in the installPhase of a `rust.buildRustPackage` in my flake's outputs, if that's relevant.

`nix build` tells me that the rustc attribute is missing in the makeRustPlatform call. The README says that all toolchains have both a rustc and cargo output, so I'm assuming that *something* has gone wrong. Any ideas about what it is? Thanks!

**Comment by figsoda** [comment]
my bad, the documentation was wrong. fromToolchainFile returns a derivation instead of a toolchain, so you can use
```nix
pkgs.makeRustPlatform {
  rustc = toolchain;
  cargo = toolchain;
}
```
instead

**Comment by lincolnauster** [comment]
Thanks for the clarification and fix - everything's working great now!
