### ISSUE TITLE
rust-analyzer-nightly in flake.nix devShell

### ISSUE THREAD

**Issue by bwolf** [nix-community/fenix#56]
I don't get according the documentation and the sources on how to get a flake-based devShell with `rust-analyzer-nightly`.

I'm using stable for build and development (i.e. 1.56.1) currently. This is my flake.nix (reduced):
```nix
{
  inputs = {
    nixpkgs.url = github:nixos/nixpkgs/nixpkgs-unstable;
    fenix = {
      url = github:nix-community/fenix;
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, fenix, flake-utils, }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        devToolchain = fenix.packages."${system}".stable; # NOTE stable
      in rec {
        devShell = pkgs.mkShell {
          nativeBuildInputs = [
            (devToolchain.withComponents [
              "cargo" "rustc" "rust-src" "rustfmt" "clippy"
            ])
            # TODO fenix.rust-analyzer-nightly
          ];
          RUST_BACKTRACE=1;
        };
      });
}
```

All I tried failed so far to get `rust-analyzer-nightly`. What I'm missing here. I also tried to apply an overlay but failed with it.

And while we're at it: Is it possible to define a toolchain of components with a specific Rust version (like pinning it to e.g. 1.56.1)?

Thanks

**Comment by figsoda** [comment]
`rust-analyzer-nightly` only exists with the overlay, you can use `fenix.packages.${system}.rust-analyzer` here

for versioned toolchains, you can do
```nix
let
  devToolchain = fenix.packages.${system}.toolchainOf {
    channel = "1.56.1";
    sha256 = "sha256-MJyH6FPVI7diJql9d+pifu5aoqejvvXyJ+6WSJDWaIA=";
  };
in

devToolchain.withComponents [
  "cargo" "rustc" "rust-src" "rustfmt" "clippy"
]
```

**Comment by bwolf** [comment]
Thank you ☜(⌒▽⌒)☞
