### ISSUE TITLE
How to install rustfmt-preview

### ISSUE THREAD

**Issue by npajkovsky** [nix-community/fenix#63]
Hey,

how can I install `rustftm-preview`? What I have now in my flake is

```
  devToolchain = fenix.packages.${system}.toolchainOf {
    channel = "1.55.0";
    sha256 = "sha256-HNIlEerJvk6sBfd8zugzwSgSiHcQH8ZbqWQn9BGfmpo=";
  };

  (devToolchain.withComponents [
    "clippy-preview"
    "rustfmt-preview"
    "rustc"
    "clippy"
    "cargo"
```

however when I enter into `nix develop`, I'm still getting stable `rustfmt`

```
rustfmt --version
rustfmt 1.4.37-stable (c8dfcfe 2021-09-06)
```

any ideas what's going on?

**Comment by figsoda** [comment]
> `channel = "1.55.0"`

this is a stable channel and this is a stable release of rustfmt

**Comment by npajkovsky** [comment]
So, there's no way to have a `stable` or `minimal stable` toolchain with unstable rustfmt features?

**Comment by figsoda** [comment]
you can use the `combine` function to put stable toolchain and nightly rustfmt together
https://github.com/nix-community/fenix#usage

**Comment by npajkovsky** [comment]
Awesome, thanks that worked. Closing.
