### ISSUE TITLE
Is there a way to use stable rustc with nightly rustdoc?

### ISSUE THREAD

**Issue by CobaltCause** [nix-community/fenix#65]
It seems like the `rustdoc` and `rustc` binaries belong to the same derivation, so using `combine` doesn't work (it just picks all binaries of whichever conflicting derivation comes last). I tried writing a custom `symlinkJoin` derivation to symlink the two derivations together and just replacing `stable.rustc`'s `rustdoc` binary with the one from `latest.rustc`, but that causes weird problems when running `cargo test` (Cargo/rustc is suddenly unable to resolve items from external crates). Making both `latest.rustc` and `stable.rustc` available and doing `cargo +nightly doc` doesn't get the desired behavior either.

**Comment by figsoda** [comment]
How did you use stable rustc with nightly rustdoc with (presumably) rustup? Also if I understood correctly, when rustup is available, `cargo +nightly doc` picks the nightly version for all the components used, not just rustdoc.

**Comment by CobaltCause** [comment]
> How did you use stable rustc with nightly rustdoc with (presumably) rustup?

I didn't, I just assumed fenix might be able to make it work since for some reason it's possible to use stable everything except nightly rustfmt, so it seemed like it should follow that it would be possible to do this with rustdoc too. So I think

> Also if I understood correctly, when rustup is available, cargo +nightly doc picks the nightly version **for all the components used, not just rustdoc**.

implies that what I wanted isn't really a thing. I guess the solution is to have a `stable` and `nightly` devshell, or pull in rustup and get the `cargo +nightly` syntax to work, or something like that. Either way I don't think there's anything fenix can do here, so I suppose I can close this.
