### ISSUE TITLE
Question: difference from oxalica/rust-overlay?

### ISSUE THREAD

**Issue by Fuuzetsu** [nix-community/fenix#78]
I've just stumbled upon this and I wonder what's different from https://github.com/oxalica/rust-overlay which we've been using for a long time.

They seem to have exactly the same goals: replacing the mozilla overlay...

Just a bit confused: is it worth to just join the effort instead?

**Comment by figsoda** [comment]
rust-overlay is bigger in size and includes all the manifests in the past

fenix requires sha256 for older toolchains and depends on ifd for things like `fromToolchainFile`, but is a lot smaller in size

If both works for you, just pick the one ur more comfortable using

**Comment by Fuuzetsu** [comment]
I see. So in this repo, stable only contains 1 version and so on. Thank you, I'll close the ticket.
