### ISSUE TITLE
Using fenix.overlay can prevent nix from downloading packages from cachix

### ISSUE THREAD

**Issue by MaeIsBad** [nix-community/fenix#79]
I ran into an issue where my laptop wasn't using the nix-community cache for fenix packages when building my system, despite using the fenix flake and not modifying the fenix nixpkgs input. This is because fenix will use `super.callPackage` in the overlay, which causes it to use the system nixpkgs and not the ones from the `fenix.inputs.nixpkgs`.

One solution is to replace the fenix overlay from the repo with a simple:
```
nixpkgs.overlays = [ (prev: _: { fenix = import fenix { system = prev.system; }) }
```

This isn't necessarily a bug, but I thought it might be worth it to document this behavior with an issue. Feel free to close or maybe consider mentioning this in the readme.

**Comment by figsoda** [comment]
Seems intended but I could be more clear about it in the readme. May I ask you what branch of nixpkgs are you using?

**Comment by MaeIsBad** [comment]
I'm using stable nixos-22.05 although I overlay some packages with their nixos-unstable counterparts

**Comment by figsoda** [comment]
does this work for you?

```nix
{
  nixpkgs.overlays = [ (self: _: fenix.overlay self self) ];
}
```

**Comment by MaeIsBad** [comment]
no, that still causes some of the fenix related packages to be built from source instead of getting pulled from cachix

**Comment by figsoda** [comment]
what about this
```nix
{
  nixpkgs.overlays = [ (_: super: (fenix.overlay { } { callPackage = x: _: import x { inherit (super) system; }; })) ];
}
```

or

```nix
{
  nixpkgs.overlays = [ (_: super: let pkgs = fenix.inputs.nixpkgs.legacyPackages.${super.system}; in fenix.overlay pkgs pkgs) ];
}
```

**Comment by MaeIsBad** [comment]
Both of those work for me, although the second one seems way cleaner

**Comment by figsoda** [comment]
I added a note to the readme

**Comment by mplanchard** [comment]
This may be obvious, but is there a way to do this if using an overlay but not using flakes?
