### ISSUE TITLE
include cargo-udeps 

### ISSUE THREAD

**Issue by blueForestIcarus** [nix-community/fenix#86]
Consider including [cargo-udeps ](https://github.com/est31/cargo-udeps)

**Comment by figsoda** [comment]
cargo-udeps is already in nixpkgs ([source](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/rust/cargo-udeps/default.nix)). Any reason you would like to have it in fenix instead?

**Comment by blueForestIcarus** [comment]
When using the one in nixpkgs it appears to use cargo in nixpkgs, which is not nightly.
(there might be a simple solution to this I am not seeing)

**Comment by blueForestIcarus** [comment]
Okay, it seems when trying it with `nix-shell -p` it clobber my cargo path. 
You're right this seems to work.
